# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cpplint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: pip install cpplint
    - run: cpplint --filter=-legal/copyright,-build/header_guard,-build/include_order --recursive .

  create_release:
    name: Build
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Install Toolchain
        shell: cmd
        run: ./gradlew installRoboRioToolchain
      - name: Build
        shell: cmd
        run: ./gradlew build
  # This workflow contains a single job called "build"
  # https://docs.wpilib.org/en/stable/docs/software/basic-programming/robot-code-ci.html
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   # This grabs the WPILib docker container
  #   container: wpilib/roborio-cross-ubuntu:2021-18.04
  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #   - uses: actions/checkout@v2
  #   # Grant execute permission for gradlew
  #   - name: Grant execute permission for gradlew
  #     run: chmod +x gradlew
  #   # Runs a single command using the runners shell
  #   # - name: Compile and run tests on robot code
  #   #   run: ./gradlew installRoboRioToolchain
  #   # Runs a single command using the runners shell
  #   - name: Compile and run tests on robot code
  #     run: ./gradlew build
